Repository UB-ES-2023-A2/kasula-backend, pull requests merged in 2023-11, with the labels that each got.

#80 Hotfix change db tests
  .github/workflows/python-app.yml
  app/app_definition.py
  app/config/.env.example
  app/config/__init__.py
  app/routers/user_router.py
  app/run_tests.py
Labels: bug

#76 [Enhancement]: Send welcome email
  .github/workflows/python-app.yml
  .gitignore
  app/app_definition.py
  app/config/.env.example
  app/config/__init__.py
  app/fake_test.py
  app/routers/user_router.py
  app/run_tests.py
  app/tests/test_recipe_endpoints.py
Labels: enhancement

#82 [Feature]: US14 Follow users
  app/models/user_model.py
  app/routers/recipe_router.py
  app/routers/user_router.py
Labels: enhancement

#83 [Bug]: Changed user_id to username in recipe
  app/app_definition.py
  app/models/recipe_model.py
  app/routers/recipe_router.py
  app/tests/test_recipe_endpoints.py
Labels: bug

#86 US8: Rate & Review recipes
  app/app_definition.py
  app/models/recipe_model.py
  app/models/review_model.py
  app/routers/recipe_router.py
  app/routers/review_router.py
Labels: enhancement

#93 [Hotfix]: Update user in recipe and review / User profile pic / Update recipe images
  app/models/recipe_model.py
  app/models/review_model.py
  app/routers/recipe_router.py
  app/routers/review_router.py
  app/routers/user_router.py
  app/tests/test_recipe_endpoints.py
  app/tests/test_user_endpoints.py
Labels: bug

#88 US4: View recipe details
  app/app_definition.py
  app/models/recipe_model.py
  app/routers/recipe_router.py
  app/tests/test_recipe_endpoints.py
Labels: enhancement

#90 US19: Privacy settings
  app/models/recipe_model.py
  app/models/review_model.py
  app/models/user_model.py
  app/routers/recipe_router.py
  app/routers/review_router.py
  app/routers/user_router.py
  app/run_tests.py
  app/tests/test_recipe_endpoints.py
  app/tests/test_user_endpoints.py
Labels: enhancement

#97 [Hotfix]: Some issues regarding recipes
  app/models/ingredient_model.py
  app/routers/recipe_router.py
  app/utils/token.py
Labels: bug

#98 [Feature]: Recipe collections
  app/app_definition.py
  app/models/collection_model.py
  app/routers/collection_router.py
  app/routers/recipe_router.py
  app/routers/user_router.py
  app/utils/token.py
Labels: enhancement

#103 [Hotfix]: Added main_image + some recipe corrections
  .gitignore
  app/models/recipe_model.py
  app/routers/recipe_router.py
Labels: bug

#106 [Hotfix]: Unlike a review
  app/routers/review_router.py
Labels: hotfix

#107 Devops correct actions
  .github/workflows/deploy.yml
  .github/workflows/test.yml
Labels: enhancement

#109 [Unit Tests]: Mock & Integration tests of collections
  app/app_definition.py
  app/routers/collection_router.py
  app/routers/recipe_router.py
  app/routers/review_router.py
  app/routers/user_router.py
  app/run_tests.py
  app/tests/test_collection_endpoints.py
  app/tests/test_user_endpoints.py
Labels: enhancement

#110 [Testing]: Add coverage report
  app/run_tests.py
  app/tests/test_security_hashing.py
  app/tests/test_token.py
  requirements.in
  requirements.txt
Labels: enhancement
